# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTb',
            fields=[
                ('lecture_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lecture_reg_count', models.IntegerField(db_column='LECTURE_REG_COUNT', default=0)),
                ('lecture_rem_count', models.IntegerField(db_column='LECTURE_REM_COUNT', default=0)),
                ('lecture_avail_count', models.IntegerField(db_column='LECTURE_AVAIL_COUNT', default=0)),
                ('day_count', models.IntegerField(blank=True, db_column='DAY_COUNT', null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('option_cd', models.CharField(blank=True, db_column='OPTION_CD', max_length=10, null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
                ('class_tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.ClassTb')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.MemberTb')),
            ],
            options={
                'db_table': 'LECTURE_TB',
                'managed': True,
            },
        ),
    ]
