# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturetb',
            name='schedule_check',
            field=models.IntegerField(blank=True, db_column='SCHEDULE_CHECK', null=True),
        ),
    ]
