# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('trainee', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturetb',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.ClassTb'),
        ),
        migrations.AddField(
            model_name='lecturetb',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.MemberTb'),
        ),
    ]
