# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_auto_20171004_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturetb',
            old_name='class_field',
            new_name='class_tb',
        ),
    ]
