# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTb',
            fields=[
                ('class_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('class_type_cd', models.CharField(blank=True, db_column='CLASS_TYPE_CD', max_length=10, null=True)),
                ('subject_cd', models.CharField(blank=True, db_column='SUBJECT_CD', max_length=10, null=True)),
                ('subject_detail_nm', models.CharField(blank=True, db_column='SUBJECT_DETAIL_NM', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('class_hour', models.FloatField(blank=True, db_column='CLASS_HOUR', null=True)),
                ('start_hour_unit', models.FloatField(blank=True, db_column='START_HOUR_UNIT', null=True)),
                ('class_member_num', models.IntegerField(blank=True, db_column='CLASS_MEMBER_NUM', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('schedule_check', models.IntegerField(blank=True, db_column='SCHEDULE_CHECK', null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CLASS_TB',
            },
        ),
        migrations.CreateModel(
            name='CompanyTb',
            fields=[
                ('company_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True)),
                ('info', models.CharField(blank=True, db_column='INFO', max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, db_column='IMG_URL', max_length=255, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'COMPANY_TB',
            },
        ),
        migrations.CreateModel(
            name='SettingTb',
            fields=[
                ('setting_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('setting_type_cd', models.CharField(db_column='SETTING_TYPE_CD', max_length=10)),
                ('setting_info', models.CharField(blank=True, db_column='SETTING_INFO', max_length=255, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SETTING_TB',
            },
        ),
        migrations.CreateModel(
            name='ShopEmployeeTb',
            fields=[
                ('shop_employee_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('member', models.CharField(db_column='MEMBER_ID', default='', max_length=20)),
                ('company', models.CharField(db_column='COMPANY_ID', default='', max_length=20)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SHOP_EMPLOYEE_TB',
            },
        ),
    ]
