# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTb',
            fields=[
                ('company_id', models.CharField(db_column='COMPANY_ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True)),
                ('info', models.CharField(blank=True, db_column='INFO', max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, db_column='IMG_URL', max_length=255, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'COMPANY_TB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettingTb',
            fields=[
                ('setting_id', models.CharField(db_column='SETTING_ID', max_length=20, primary_key=True, serialize=False)),
                ('member', models.CharField(db_column='MEMBER_ID', default='', max_length=20)),
                ('setting_type_cd', models.CharField(db_column='SETTING_TYPE_CD', max_length=10)),
                ('setting_cd', models.CharField(blank=True, db_column='SETTING_CD', max_length=10, null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'SETTING_TB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShopEmployeeTb',
            fields=[
                ('shop_employee_id', models.CharField(db_column='SHOP_EMPLOYEE_ID', max_length=20, primary_key=True, serialize=False)),
                ('member', models.CharField(db_column='MEMBER_ID', default='', max_length=20)),
                ('company', models.CharField(db_column='COMPANY_ID', default='', max_length=20)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'SHOP_EMPLOYEE_TB',
                'managed': True,
            },
        ),
    ]
