# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingtb',
            name='setting_cd',
        ),
        migrations.RemoveField(
            model_name='settingtb',
            name='state_cd',
        ),
        migrations.AddField(
            model_name='classtb',
            name='schedule_check',
            field=models.IntegerField(blank=True, db_column='SCHEDULE_CHECK', null=True),
        ),
        migrations.AddField(
            model_name='settingtb',
            name='setting_info',
            field=models.CharField(blank=True, db_column='SETTING_INFO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingtb',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.MemberTb'),
        ),
    ]
