# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRepeatScheduleTb',
            fields=[
                ('class_repeat_schedule_id', models.CharField(db_column='CLASS_REPEAT_SCHEDULE_ID', max_length=20, primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='CLASS_ID', default='', max_length=20)),
                ('repeat_type_cd', models.CharField(blank=True, db_column='REPEAT_TYPE_CD', max_length=10, null=True)),
                ('week_cd', models.CharField(blank=True, db_column='WEEK_CD', max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='START_TIME', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='END_TIME', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CLASS_REPEAT_SCHEDULE_TB',
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleTb',
            fields=[
                ('class_schedule_id', models.CharField(db_column='CLASS_SCHEDULE_ID', max_length=20, primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='CLASS_ID', default='', max_length=20)),
                ('start_dt', models.DateTimeField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CLASS_SCHEDULE_TB',
            },
        ),
        migrations.CreateModel(
            name='ClassTb',
            fields=[
                ('class_id', models.CharField(db_column='CLASS_ID', max_length=20, primary_key=True, serialize=False)),
                ('member', models.CharField(db_column='MEMBER_ID', default='', max_length=20)),
                ('class_type_cd', models.CharField(blank=True, db_column='CLASS_TYPE_CD', max_length=10, null=True)),
                ('subject_cd', models.CharField(blank=True, db_column='SUBJECT_CD', max_length=10, null=True)),
                ('subject_detail_nm', models.CharField(blank=True, db_column='SUBJECT_DETAIL_NM', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('class_hour', models.FloatField(blank=True, db_column='CLASS_HOUR', null=True)),
                ('start_hour_unit', models.FloatField(blank=True, db_column='START_HOUR_UNIT', null=True)),
                ('class_member_num', models.IntegerField(blank=True, db_column='CLASS_MEMBER_NUM', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CLASS_TB',
            },
        ),
        migrations.CreateModel(
            name='LectureScheduleTb',
            fields=[
                ('lecture_schedule_id', models.CharField(db_column='LECTURE_SCHEDULE_ID', max_length=20, primary_key=True, serialize=False)),
                ('lecture', models.CharField(db_column='LECTURE_ID', default='', max_length=20)),
                ('start_dt', models.DateTimeField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('sign_data_url', models.CharField(blank=True, db_column='SIGN_DATA_URL', max_length=255, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'LECTURE_SCHEDULE_TB',
            },
        ),
        migrations.CreateModel(
            name='LectureTb',
            fields=[
                ('lecture_id', models.CharField(db_column='LECTURE_ID', max_length=20, primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='CLASS_ID', default='', max_length=20)),
                ('member', models.CharField(db_column='MEMBER_ID', default='', max_length=20)),
                ('lecture_count', models.IntegerField(blank=True, db_column='LECTURE_COUNT', null=True)),
                ('day_count', models.IntegerField(blank=True, db_column='DAY_COUNT', null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('option_cd', models.CharField(blank=True, db_column='OPTION_CD', max_length=10, null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'LECTURE_TB',
            },
        ),
    ]
