# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRepeatScheduleTb',
            fields=[
                ('delete_repeat_schedule_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('repeat_schedule_id', models.IntegerField(db_column='REPEAT_SCHEDULE_ID')),
                ('repeat_type_cd', models.CharField(blank=True, db_column='REPEAT_TYPE_CD', max_length=10, null=True)),
                ('week_info', models.CharField(blank=True, db_column='WEEK_INFO', max_length=10, null=True)),
                ('start_dt', models.DateField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'DELETE_REPEAT_SCHEDULE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeleteScheduleTb',
            fields=[
                ('delete_schedule_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('schedule_id', models.IntegerField(db_column='SCHEDULE_ID')),
                ('delete_repeat_schedule_tb', models.IntegerField(blank=True, db_column='DELETE_REPEAT_SCHEDULE_TB_ID', null=True)),
                ('start_dt', models.DateTimeField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('sign_data_url', models.CharField(blank=True, db_column='SIGN_DATA_URL', max_length=255, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'DELETE_SCHEDULE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatScheduleTb',
            fields=[
                ('repeat_schedule_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('repeat_type_cd', models.CharField(blank=True, db_column='REPEAT_TYPE_CD', max_length=10, null=True)),
                ('week_info', models.CharField(blank=True, db_column='WEEK_INFO', max_length=10, null=True)),
                ('start_dt', models.DateField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
            ],
            options={
                'db_table': 'REPEAT_SCHEDULE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleTb',
            fields=[
                ('schedule_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField(blank=True, db_column='START_DT', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='END_DT', null=True)),
                ('state_cd', models.CharField(blank=True, db_column='STATE_CD', max_length=10, null=True)),
                ('sign_data_url', models.CharField(blank=True, db_column='SIGN_DATA_URL', max_length=255, null=True)),
                ('en_dis_type', models.CharField(blank=True, db_column='EN_DIS_TYPE', max_length=10, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
            ],
            options={
                'db_table': 'SCHEDULE_TB',
                'managed': False,
            },
        ),
    ]
