# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        ('trainee', '0003_auto_20171005_1904'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrepeatscheduletb',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='classscheduletb',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='lecturescheduletb',
            name='lecture',
        ),
        migrations.AddField(
            model_name='classrepeatscheduletb',
            name='class_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trainer.ClassTb'),
        ),
        migrations.AddField(
            model_name='classscheduletb',
            name='class_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trainer.ClassTb'),
        ),
        migrations.AddField(
            model_name='lecturescheduletb',
            name='lecture_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trainee.LectureTb'),
        ),
    ]
