# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterTb',
            fields=[
                ('center_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('center_name', models.CharField(blank=True, db_column='CENTER_NAME', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=255, null=True)),
                ('center_type_cd', models.CharField(blank=True, db_column='CENTER_TYPE_CD', max_length=20, null=True)),
                ('center_img_url', models.CharField(blank=True, db_column='CENTER_IMG_URL', max_length=255, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'CENTER_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CenterTrainerTb',
            fields=[
                ('center_trainer_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'db_table': 'CENTER_TRAINER_TB',
                'managed': False,
            },
        ),
    ]
