OFF_SCHEDULE_TYPE = '0'
ON_SCHEDULE_TYPE = '1'
GROUP_SCHEDULE_TYPE = '2'
CLASS_SCHEDULE_TYPE = '2'
REPEAT_TYPE_WEAK = 'WW'
REPEAT_TYPE_2WEAK = '2W'
DEL_SCHEDULE = 0
ADD_SCHEDULE = 1

USE = 1
UN_USE = 0

ACTIVATE = 1
DEACTIVATE = 0

FREE_GROUP = 'EMPTY'
FIXED_GROUP = 'NORMAL'

AUTO_CANCEL_ON = 3
AUTO_ABSENCE_ON = 2
AUTO_FINISH_ON = 1
AUTO_FINISH_OFF = 0

MEMBER_RESERVE_PROHIBITION_ON = 1
MEMBER_RESERVE_PROHIBITION_OFF = 0

STATS_SALES = 'SALES'
STATS_MEMBER = 'MEMBER'

STATS_NEW_REG = 0
STATS_RE_REG = 1
STATS_ALL_REFUND = 2
STATS_PART_REFUND = 3

SCHEDULE_NOT_FINISH = 0
SCHEDULE_FINISH = 1
SCHEDULE_ABSENCE = 2

TO_TRAINEE_LESSON_ALARM_ON = 1
TO_TRAINEE_LESSON_ALARM_OFF = 0

FROM_TRAINEE_LESSON_ALARM_ON = 1
FROM_TRAINEE_LESSON_ALARM_OFF = 0

SCHEDULE_DUPLICATION_DISABLE = 0
SCHEDULE_DUPLICATION_ENABLE = 1

SORT_MEMBER_NAME = 0
SORT_REMAIN_COUNT = 1
SORT_START_DATE = 2
SORT_REG_COUNT = 3
SORT_END_DATE = 4

SORT_LECTURE_NAME = 0
SORT_LECTURE_MEMBER_COUNT = 1
SORT_LECTURE_CAPACITY_COUNT = 2
SORT_LECTURE_CREATE_DATE = 3

SORT_TICKET_TYPE = 0
SORT_TICKET_NAME = 1
SORT_TICKET_MEMBER_COUNT = 2
SORT_TICKET_CREATE_DATE = 3

SORT_MEMBER_TICKET = 0
SORT_SCHEDULE_DT = 1

SORT_ASC = 0
SORT_DESC = 1

ING_MEMBER_FALSE = 0
ING_MEMBER_TRUE = 1

PROGRAM_SELECT = 0
PROGRAM_LECTURE_CONNECT_ACCEPT = 1
PROGRAM_LECTURE_CONNECT_DELETE = 2

OFF_SCHEDULE = 0
ON_SCHEDULE = 1
GROUP_SCHEDULE = 2


STATE_CD_NOT_PROGRESS = 'NP'
STATE_CD_IN_PROGRESS = 'IP'
STATE_CD_FINISH = 'PE'
STATE_CD_ABSENCE = 'PC'
STATE_CD_REFUND = 'RF'
PERMISSION_STATE_CD_APPROVE = 'AP'


LECTURE_TYPE_ONE_TO_ONE = 'ONE_TO_ONE'
LECTURE_TYPE_NORMAL = 'NORMAL'

AUTH_TYPE_VIEW = 'VIEW'
AUTH_TYPE_DELETE = 'DELETE'
AUTH_TYPE_WAIT = 'WAIT'

SHOW = 0
HIDE = 1

SUNDAY = 'SUN'
MONDAY = 'MON'

BOARD_TYPE_CD_BOARD = 'BOARD'
BOARD_TYPE_CD_NOTICE = 'NOTICE'
BOARD_TYPE_CD_QA = 'QA'

NOTICE_TYPE_CD_NORMAL = 'NORMAL'
NOTICE_TYPE_CD_URGENT = 'URGENT'

TO_MEMBER_BOARD_TYPE_CD_ALL = 'ALL'
TO_MEMBER_BOARD_TYPE_CD_TRAINER = 'TRAINER'
TO_MEMBER_TBOARD_YPE_CD_TRAINEE = 'TRAINEE'


CALENDAR_TIME_SELECTOR_BASIC = '0'
CALENDAR_TIME_SELECTOR_ORIGIN = '1'
