OFF_SCHEDULE_TYPE = '0'
ON_SCHEDULE_TYPE = '1'
GROUP_SCHEDULE_TYPE = '2'
REPEAT_TYPE_WEAK = 'WW'
REPEAT_TYPE_2WEAK = '2W'
DEL_SCHEDULE = 0
ADD_SCHEDULE = 1

USE = 1
UN_USE = 0

FREE_GROUP = 'EMPTY'
FIXED_GROUP = 'NORMAL'

AUTO_FINISH_ON = 1
AUTO_FINISH_OFF = 0

MEMBER_RESERVE_PROHIBITION_ON = 1
MEMBER_RESERVE_PROHIBITION_OFF = 0
