# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaytb',
            name='holiday_dt',
            field=models.CharField(blank=True, db_column='HOLIDAY_DT', max_length=10, null=True),
        ),
    ]
