# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=2, null=True)),
                ('birthday_dt', models.DateField(blank=True, db_column='BIRTHDAY_DT', null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=255, null=True)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=20, null=True)),
                ('contents', models.CharField(blank=True, db_column='CONTENTS', max_length=255, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, db_column='REG_DT', null=True)),
                ('mod_dt', models.DateTimeField(blank=True, db_column='MOD_DT', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', default='1', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROFILE_TB',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='membertb',
            name='birthday_dt',
            field=models.DateField(blank=True, db_column='BIRTHDAY_DT', null=True),
        ),
    ]
